// <auto-generated />
using System;
using AccessModuleSystem.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AccessModuleSystem.Server.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250117213814_editUser_add_fields")]
    partial class editUser_add_fields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccessModuleSystem.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Patronymic")
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1b0f2cc-79b3-4b69-928c-8b263f2ab9c4"),
                            CreatedAt = new DateTime(2023, 6, 16, 0, 37, 19, 0, DateTimeKind.Utc),
                            Email = "admin@ams.ru",
                            Name = "Павел",
                            PasswordHash = "admin",
                            Role = 0,
                            Surname = "Маркелов",
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("d1b0f4cc-79b3-4b69-988c-8b263f2ab9c4"),
                            CreatedAt = new DateTime(2023, 5, 16, 0, 37, 19, 0, DateTimeKind.Utc),
                            Email = "user@ams.ru",
                            Name = "Иван",
                            PasswordHash = "user",
                            Role = 1,
                            Surname = "Иванов",
                            Username = "user"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
